name: LeetVault
main: Marcel2508\LeetVault
version: 1.1.0
api: [3.0.0-ALPHA10]
load: STARTUP
author: Marcel2508
description: Allows you to use virtual chest inventories

commands:
 lv:
  usage: /lv [clear/#vaultNo/help] [#vaultNo (if clear is given)]
  aliases: ["leetvault"]
  permission: leetvault.use
 lva:
  usage: /lva <#vaultNo/clear/setlimit> <playername/(#vaultNo/all)/#limit> [playername (if clear is given)]
  aliases: ["leetvaultadmin"]
  permission: leetvault.admin
permissions:
    leetvault.use:
        default: true
        description: Allows players to use all basic commands
    leetvault.admin:
        default: false
        description: Allows players to use all admin commands